# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/alpine/.devcontainer/base.Dockerfile

# [Choice] Alpine version: 3.14, 3.13, 3.12, 3.11
# HB1: It seems that build.args doesn't pass to Dockerfile build from .devcontainer:
ARG VARIANT="3.14"

FROM vsc-snapd-github-public-master-live-devcontainer-alpine:latest
