# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/alpine/.devcontainer/base.Dockerfile

# [Choice] Alpine version: 3.14, 3.13, 3.12, 3.11
# HB1: It seems that build.args and below ARGs doesn't pass to Dockerfile build from .devcontainer:
ARG remoteUser=vscode
ARG VARIANT="3.15"
ARG PROJECTS_DIR=/projects
ARG DATA_DIR=${PROJECTS_DIR}/data
ARG CONTEXT_DIR="${PROJECTS_DIR}/snapd/snapd-github-public-master-live-devcontainer-alpine"

ARG PACKAGER_NAME="Henrik Bach"
ARG PACKAGER_EMAIL="bach.henrik@gmail.com"

FROM mcr.microsoft.com/vscode/devcontainers/base:0-alpine-${VARIANT}

ENV remoteUser=vscode

COPY scripts/postStartCommand-Alpine.sh /postStartCommand-Alpine.sh
RUN chmod a+wx /postStartCommand-Alpine.sh

RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        doas \
        sudo

RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        alpine-sdk \
        atools \
        curl \
        fennel \
        git \
        lua5.3-dev \
        luarocks5.3 \
        make \
        nano \
        openrc \
        openssl-dev \
        sed \
        shadow \
        su-exec \
        tree \
        util-linux \
        wget

# snapd builddeps:
RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        apparmor \
        git \
        go \
        libcap \
        libseccomp \
        shellcheck \
        squashfs-tools \
        xfsprogs

        # systemd \
        # libsystemd \
        # go-tools \

        # python \
        # python-docutils \
# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

RUN echo "$remoteUser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN echo "permit nopass keepenv :$remoteUser" | sudo tee -a /etc/doas.conf

###############################################################################
# Switch to remoteUser
###############################################################################

# Following overall: https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package:

USER $remoteUser

RUN doas addgroup $remoteUser abuild
